# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
 vmImage: 'ubuntu-latest'
trigger:
- none

pool:
  vmImage: $(vmImage)

steps:
 - task: Maven@3
   inputs:
     mavenPomFile: 'pom.xml'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     mavenVersionOption: 'Default'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: false
     sqMavenPluginVersionChoice: 'latest'
     checkStyleRunAnalysis: true
     findBugsRunAnalysis: true

 - task: CopyFiles@2
   displayName: copying files form source directory
   inputs:
     contents: 'target/*.jar'
     CleanTargetFolder: true
     TargetFolder: $(build.artifactstagingdirectory)
     OverWrite: true
     retryCount: '5'
     preserveTimestamp: true
     delayBetweenRetries: true